# Port HTTPS (Tomcat embedded)
server.port=8443

# Habilitar SSL
server.ssl.enabled=true

# Ruta del Keystore generat amb keytool
server.ssl.key-store=classpath:keystore.p12
server.ssl.key-store-password=Collonarro
server.ssl.key-store-type=PKCS12
server.ssl.key-alias=tomcat

# Forçar TLS 1.3 (Objectiu a l'enunciat)
server.ssl.enabled-protocols=TLSv1.3

# Xifratges segurs (Equivalent a SSLCipherSuite)
server.ssl.ciphers=TLS_AES_256_GCM_SHA384,TLS_CHACHA20_POLY1305_SHA256

# Clau AES-256 per al servei de xifrat (64 caràcters hex = 32 bytes = 256 bits)
app.security.aes-key=24dbd51343b440b965c9605ce596c3a5e1b11ed07d4abd48556d7971d0d6ed12
